{{ if and (not .Values.global.externalOpensearch.enabled) (eq (include "opensearch.shouldRunMigration" .) "true") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opensearch.fullname" . }}-migration
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ template "opensearch.fullname" . }}-migration
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-migration
    app.kubernetes.io/instance: {{ cat (printf "%s-migration"  (include "opensearch.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
