{{- if and (eq .Values.DEPLOY_MODE "RollingUpdate") (eq (include "opensearch.imageVariant" .) "3") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-validate-opensearch-upgrade
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-180"
subjects:
  - kind: ServiceAccount
    name: {{ template "opensearch.fullname" . }}-validate-opensearch-upgrade
roleRef:
  kind: Role
  name: {{ template "opensearch.fullname" . }}-validate-opensearch-upgrade
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
